### ISSUE TITLE
adapt the belonging survey to your thesis

### ISSUE THREAD

**Issue by hcientist** [Lab-Lab-Lab/bbb-thesis#2]
https://dl.acm.org/doi/10.1145/3408877.3432425
probably we cite our colleagues above as well as the original https://jmu.primo.exlibrisgroup.com/discovery/openurl?institution=01JMU_INST&vid=01JMU_INST:01JMU&url_ver=Z39.88-2004&rft_id=info:doi%2F10.1037%2Fa0026659

**Comment by mfwolffe** [comment]
@hcientist see: [overleaf](https://www.overleaf.com/project/66d915552043409095daace4)
you should have access!

**Comment by hcientist** [comment]
@mfwolffe `Restricted, sorry you don’t have permission to load this page.`

**Comment by mfwolffe** [comment]
@hcientist reviewed together Thursday
